# Generated by Django 3.2.9 on 2021-11-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(null=True, upload_to='platos'),
        ),
    ]
