# Generated by Django 3.2.8 on 2021-10-31 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('ID_Producto', models.UUIDField(default=uuid.uuid4, help_text='id unica para producto', primary_key=True, serialize=False)),
                ('Nombre_producto', models.CharField(max_length=100)),
                ('Stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=200)),
            ],
        ),
    ]
