//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Nombre { get; set; }
        public string Rut { get; set; }
        public string contraseña { get; set; }
        public string email { get; set; }
        public string TipoUsuario { get; set; }
    }
}
